# Automatically add commits to fix pull requests. This workflow must initiate
# from an authenticated bot repo collaborator. Check for opt-out label.
# Webhook events: Pull requests
name: Auto-fix pull request
on:
  repository_dispatch:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  nbfmt:
    name: Fix notebook formatting
    # Check for opt-out label.
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install tensorflow-docs
      run: python3 -m pip install -U git+https://github.com/tensorflow/docs
    - name: Fetch pull request branch
      uses: actions/checkout@v2
      with:
        # Head repo is the user's fork. Ref is the branch name.
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.sha }}
    - name: Fetch base master branch
      run: git fetch -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" master:master
    - name: Format notebooks
      run: |
        echo "Hello World!"

  nblint-fix:
    name: Fix lint warnings
    # Check for opt-out label.
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install tensorflow-docs
      run: python3 -m pip install -U git+https://github.com/tensorflow/docs
    - name: Fetch pull request branch
      uses: actions/checkout@v2
      with:
        # Head repo is the user's fork. Ref is the branch name.
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}
    - name: Fetch base master branch
      run: git fetch -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" master:master
    - name: Fix lint warnings in notebooks
      run: |
        echo "Hello World!"
